#!/usr/bin/perl

# sonos-cli - Command line interface to control 'Sonos ZonePlayer' 
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2010 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

use warnings;
use strict;
use Net::UPnP::ControlPoint;
use Getopt::Long;

my $O_TIMEOUT = 3;
my $O_MODE = 'status';

GetOptions(
    'mode=s' => \$O_MODE,
    'timeout=i' => \$O_TIMEOUT,
);

my %commands = (
    Play => {
	title => 'play media',
	sargs => { Speed => 1 },
    },
    Pause => {
	title => 'pause media',
    },
    Stop => {
	title => 'stop media',
    },
    Next => {
	title => 'jump to next',
    },
    Previous => {
	title => 'jump to previous',
    },
);

my $cp = Net::UPnP::ControlPoint->new();
my @devs = $cp->search(st =>'urn:schemas-upnp-org:device:ZonePlayer:1', mx => $O_TIMEOUT);

my $devNum= 0;
my %devices;
foreach my $dev (@devs) {
    $devNum++;

    print "[$devNum]\n";

    my $avt = $dev->getservicebyname('urn:schemas-upnp-org:service:AVTransport:1');
    my %avt_args = (
	'InstanceID' => 0,
    );
    my $rcode;

    my $cmd = ucfirst(lc($O_MODE));
    if(exists($commands{$cmd})) {
	%avt_args = (%avt_args, %{$commands{$cmd}->{'sargs'}}) if(defined($commands{$cmd}->{'sargs'}));
	$rcode = $avt->postaction($cmd, \%avt_args)->getstatuscode();
    }
}
