#!/usr/bin/perl

# sonos-cli - Command line interface to control 'Sonos ZonePlayer' 
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2010 - 2012 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

use warnings;
use strict;
use Net::UPnP::ControlPoint;
use Getopt::Long;

use constant {
    STATUS_OK => 200,

    SRV_DeviceProperties => 'urn:schemas-upnp-org:service:DeviceProperties:1',
    SRV_AVTransport => 'urn:schemas-upnp-org:service:AVTransport:1',
};

my $O_TIMEOUT = 3;
my $O_MODE = 'status';

GetOptions(
    'mode=s' => \$O_MODE,
    'timeout=i' => \$O_TIMEOUT,
);

my %commands = (
    Play => {
	title => 'play media',
	aargs => { Speed => 1 },
    },
    Pause => {
	title => 'pause media',
    },
    Stop => {
	title => 'stop media',
    },
    Next => {
	title => 'jump to next',
    },
    Previous => {
	title => 'jump to previous',
    },
    Snooze => {
	title => 'snooze active alarm',
	action => 'SnoozeAlarm',
	aargs => { Duration => 7*60 },
    }
);

my $cp = Net::UPnP::ControlPoint->new();
my @devs = $cp->search(st =>'urn:schemas-upnp-org:device:ZonePlayer:1', mx => $O_TIMEOUT);

my $devNum= 0;
my %devices;
my $cmd = ucfirst(lc($O_MODE));
foreach my $dev (@devs) {
    $devNum++;

    print "[$devNum] ";

    my %services;
    $services{(SRV_DeviceProperties)} = $dev->getservicebyname(SRV_DeviceProperties);
    $services{(SRV_AVTransport)} = $dev->getservicebyname(SRV_AVTransport);

    my $aresp = $services{(SRV_DeviceProperties)}->postaction('GetZoneAttributes');
    if($aresp->getstatuscode != STATUS_OK) {
	print STDERR "Got error code ".$aresp->getstatuscode."!\n";
	next;
    }
    my $aresu = $aresp->getargumentlist;
    print $aresu->{CurrentZoneName}, ": ";


    my %aargs = (
	'InstanceID' => 0,
    );

    if(exists($commands{$cmd})) {
	my %_aargs = (%aargs, %{$commands{$cmd}->{aargs}}) if(exists($commands{$cmd}->{aargs}));
	$aresp = $services{(SRV_AVTransport)}->postaction((exists($commands{$cmd}->{action}) ? $commands{$cmd}->{action} : $cmd), \%_aargs);
	if($aresp->getstatuscode != STATUS_OK) {
	    print STDERR "Got error code ".$aresp->getstatuscode."!\n";
	    next;
	}
    }

    $aresp = $services{(SRV_AVTransport)}->postaction('GetTransportInfo', \%aargs);
    if($aresp->getstatuscode != STATUS_OK) {
	print STDERR "Got error code ".$aresp->getstatuscode."!\n";
	next;
    }

    $aresu = $aresp->getargumentlist;
    print $aresu->{CurrentTransportState}, "\n";
}
