#!/usr/bin/perl

# sonos-cli - Command line interface to control 'Sonos ZonePlayer' 
#
# Authors:
#   Thomas Liske <thomas@fiasko-nw.net>
#
# Copyright Holder:
#   2010 - 2014 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]
#
# License:
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this package; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

use warnings;
use strict;
use Getopt::Std;
use Net::UPnP::SONOS;

$Getopt::Std::STANDARD_HELP_VERSION++;

sub HELP_MESSAGE {
    print <<USG;
Usage:

  sosh [-h <host>] [-p <port>]

    -h <host>	sonos-backend host [::1]
    -p <port>   sonos-backend listen port [1400]
    --help      show this help
    --version   show version information

This is a sonos shell/pipe to execute a batch of sonos
commands.

USG
}

sub VERSION_MESSAGE {
    print <<LIC;

sonos-cli $Net::UPnP::SONOS::VERSION - Command line interface to control 'Sonos ZonePlayer' 

Authors:
  Thomas Liske <thomas\@fiasko-nw.net>

Copyright Holder:
  2010 - 2014 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]

Upstream:
  https://github.com/liske/sonos-cli

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

LIC
#/
}

our $opt_h = '::1';
our $opt_p = 1400;
unless(getopts('h:p:')) {
    HELP_MESSAGE;
    exit 1;
}
